package com.randomlychosenbytes.jlocker.model

import com.google.gson.annotations.Expose
import com.randomlychosenbytes.jlocker.DataManager
import java.awt.BorderLayout
import java.awt.Color
import java.awt.Font
import java.awt.GridLayout
import java.awt.event.MouseAdapter
import java.awt.event.MouseEvent
import java.util.*
import javax.swing.GroupLayout
import javax.swing.JLabel
import javax.swing.JOptionPane
import javax.swing.JPanel

class LockerCabinet : Module() {

    @Expose
    var lockers: MutableList<Locker>

    companion object {
        private val dataManager = DataManager

        @JvmStatic
        fun updateDummyRows(cabinets: List<LockerCabinet>) {
            val maxRows = cabinets.map { it.lockers.size }.maxOrNull() ?: 0
            cabinets.forEach { it.updateDummyRows(maxRows) }
        }
    }

    private fun updateDummyRows(numRowsOverall: Int) {
        cabinetPanel.removeAll()
        if (numRowsOverall > lockers.size) {
            for (i in 0 until numRowsOverall - lockers.size) {
                cabinetPanel.add(JLabel())
            }
        }
        for (locker in lockers) {
            cabinetPanel.add(locker)
        }
        cabinetPanel.updateUI()
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private fun initComponents() {
        buttonPanel = JPanel()
        addLockerLabel = JLabel()
        remLockerLabel = JLabel()
        cabinetPanel = JPanel()
        layout = BorderLayout()
        buttonPanel.background = Color(177, 192, 138)
        addLockerLabel.font = Font("Tahoma", 1, 18) // NOI18N
        addLockerLabel.foreground = Color(131, 150, 81)
        addLockerLabel.text = "+"
        addLockerLabel.addMouseListener(object : MouseAdapter() {
            override fun mouseReleased(evt: MouseEvent) {
                addLockerLabelMouseReleased(evt)
            }
        })
        buttonPanel.add(addLockerLabel)
        remLockerLabel.font = Font("Tahoma", 1, 18) // NOI18N
        remLockerLabel.foreground = Color(131, 150, 81)
        remLockerLabel.text = "-"
        remLockerLabel.addMouseListener(object : MouseAdapter() {
            override fun mouseReleased(evt: MouseEvent) {
                remLockerLabelMouseReleased(evt)
            }
        })
        buttonPanel.add(remLockerLabel)
        add(buttonPanel, BorderLayout.NORTH)
        cabinetPanel.background = Color(177, 192, 138)
        val cabinetPanelLayout = GroupLayout(cabinetPanel)
        cabinetPanel.layout = cabinetPanelLayout
        cabinetPanelLayout.setHorizontalGroup(
            cabinetPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGap(0, 170, Short.MAX_VALUE.toInt())
        )
        cabinetPanelLayout.setVerticalGroup(
            cabinetPanelLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGap(0, 233, Short.MAX_VALUE.toInt())
        )
        add(cabinetPanel, BorderLayout.CENTER)
    } // </editor-fold>//GEN-END:initComponents

    private fun addLockerLabelMouseReleased(evt: MouseEvent) //GEN-FIRST:event_addLockerLabelMouseReleased
    { //GEN-HEADEREND:event_addLockerLabelMouseReleased
        lockers.add(0, Locker())
        updateDummyRows(dataManager.currentManagmentUnitList.map { it.module }.filterIsInstance<LockerCabinet>())
        remLockerLabel.isEnabled = true
    } //GEN-LAST:event_addLockerLabelMouseReleased

    private fun remLockerLabelMouseReleased(evt: MouseEvent) //GEN-FIRST:event_remLockerLabelMouseReleased
    { //GEN-HEADEREND:event_remLockerLabelMouseReleased
        if (lockers.isNotEmpty()) {
            val answer = JOptionPane.showConfirmDialog(
                null,
                "Wollen Sie dieses Schließfach wirklich löschen?",
                "Löschen",
                JOptionPane.YES_NO_CANCEL_OPTION
            )
            if (answer == JOptionPane.YES_OPTION) {
                lockers.removeAt(0) // remove first
                updateDummyRows(dataManager.currentManagmentUnitList.map { it.module }
                    .filterIsInstance<LockerCabinet>())
            }
        }
    } //GEN-LAST:event_remLockerLabelMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lateinit var addLockerLabel: JLabel
    private lateinit var buttonPanel: JPanel
    private lateinit var cabinetPanel: JPanel
    private lateinit var remLockerLabel: JLabel

    override fun toString() = "Schließfachschrank"

    init {
        initComponents()
        lockers = LinkedList()
        cabinetPanel.layout = GridLayout(0, 1, 0, 10)
        updateDummyRows(0)
    }
}