package com.randomlychosenbytes.jlocker.model

import com.google.gson.annotations.Expose
import com.randomlychosenbytes.jlocker.State
import com.randomlychosenbytes.jlocker.dialogs.ChooseManagementUnitTypeDialog
import java.awt.*
import java.awt.event.MouseAdapter
import java.awt.event.MouseEvent
import javax.swing.ImageIcon
import javax.swing.JLabel
import javax.swing.JOptionPane
import javax.swing.JPanel

class ModuleWrapper(module: Module) : JPanel() {

    @Expose
    var module: Module = module
        set(value) {
            field = value
            updatePanel()
        }

    private fun updatePanel() {
        centerPanel.apply {
            removeAll()
            add(module)
            updateUI()
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private fun initComponents() {
        centerPanel = JPanel()
        southPanel = JPanel()
        addMUnitLeftLabel = JLabel()
        transformLabel = JLabel()
        removeThisMUnitLabel = JLabel()
        addMUnitRightLabel = JLabel()
        background = Color(177, 192, 138)
        minimumSize = Dimension(125, 72)
        preferredSize = Dimension(125, 72)
        layout = GridBagLayout()
        centerPanel.background = Color(177, 192, 138)
        centerPanel.layout = BorderLayout()
        var gridBagConstraints: GridBagConstraints = GridBagConstraints()
        gridBagConstraints.gridwidth = GridBagConstraints.REMAINDER
        gridBagConstraints.fill = GridBagConstraints.BOTH
        gridBagConstraints.weightx = 1.0
        gridBagConstraints.weighty = 1.0
        gridBagConstraints.insets = Insets(10, 10, 10, 10)
        add(centerPanel, gridBagConstraints)
        southPanel.background = Color(177, 192, 138)
        addMUnitLeftLabel.font = Font("Tahoma", 1, 18) // NOI18N
        addMUnitLeftLabel.foreground = Color(131, 150, 81)
        addMUnitLeftLabel.text = "+"
        addMUnitLeftLabel.addMouseListener(object : MouseAdapter() {
            override fun mouseReleased(evt: MouseEvent) {
                addMUnitLeftLabelMouseReleased(evt)
            }
        })
        southPanel.add(addMUnitLeftLabel)
        transformLabel.icon = ImageIcon(javaClass.getResource("/gear.png")) // NOI18N
        transformLabel.addMouseListener(object : MouseAdapter() {
            override fun mouseReleased(evt: MouseEvent) {
                transformLabelMouseReleased(evt)
            }
        })
        southPanel.add(transformLabel)
        removeThisMUnitLabel.font = Font("Tahoma", 1, 18) // NOI18N
        removeThisMUnitLabel.foreground = Color(131, 150, 81)
        removeThisMUnitLabel.text = "-"
        removeThisMUnitLabel.addMouseListener(object : MouseAdapter() {
            override fun mouseReleased(evt: MouseEvent) {
                removeThisMUnitLabelMouseReleased(evt)
            }
        })
        southPanel.add(removeThisMUnitLabel)
        addMUnitRightLabel.font = Font("Tahoma", 1, 18) // NOI18N
        addMUnitRightLabel.foreground = Color(131, 150, 81)
        addMUnitRightLabel.text = "+"
        addMUnitRightLabel.addMouseListener(object : MouseAdapter() {
            override fun mouseReleased(evt: MouseEvent) {
                addMUnitRightLabelMouseReleased(evt)
            }
        })
        southPanel.add(addMUnitRightLabel)
        gridBagConstraints = GridBagConstraints()
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL
        gridBagConstraints.insets = Insets(10, 5, 10, 5)
        add(southPanel, gridBagConstraints)
    } // </editor-fold>//GEN-END:initComponents

    private fun addMUnitLeftLabelMouseReleased(evt: MouseEvent) //GEN-FIRST:event_addMUnitLeftLabelMouseReleased
    { //GEN-HEADEREND:event_addMUnitLeftLabelMouseReleased
        val mus = State.dataManager.currentManagmentUnitList
        val index = mus.indexOf(this)
        val iNewIndex: Int = if (index == mus.size - 1) {
            mus.add(ModuleWrapper(LockerCabinet()))
            mus.size - 1
        } else {
            mus.add(index + 1, ModuleWrapper(LockerCabinet()))
            index + 1
        }
        State.dataManager.currentManagementUnitIndex = iNewIndex
        State.dataManager.currentLockerIndex = 0
        State.dataManager.mainFrame.drawLockerOverview()
    } //GEN-LAST:event_addMUnitLeftLabelMouseReleased

    private fun transformLabelMouseReleased(evt: MouseEvent) //GEN-FIRST:event_transformLabelMouseReleased
    { //GEN-HEADEREND:event_transformLabelMouseReleased
        // TODO mainframe as first argument
        val dialog = ChooseManagementUnitTypeDialog(null, true, this)
        dialog.isVisible = true
    } //GEN-LAST:event_transformLabelMouseReleased

    private fun removeThisMUnitLabelMouseReleased(evt: MouseEvent) //GEN-FIRST:event_removeThisMUnitLabelMouseReleased
    { //GEN-HEADEREND:event_removeThisMUnitLabelMouseReleased
        if (State.dataManager.currentManagmentUnitList.size <= 1) {
            return
        }

        val answer = JOptionPane.showConfirmDialog(
            null,
            "Wollen Sie diesen ${this.module} wirklich löschen?",
            "Löschen",
            JOptionPane.YES_NO_CANCEL_OPTION
        )
        if (answer == JOptionPane.YES_OPTION) {
            val mus = State.dataManager.currentManagmentUnitList
            mus.remove(this)
            State.dataManager.mainFrame.drawLockerOverview()
        }
    } //GEN-LAST:event_removeThisMUnitLabelMouseReleased

    private fun addMUnitRightLabelMouseReleased(evt: MouseEvent) //GEN-FIRST:event_addMUnitRightLabelMouseReleased
    { //GEN-HEADEREND:event_addMUnitRightLabelMouseReleased
        val mus = State.dataManager.currentManagmentUnitList
        val index = mus.indexOf(this)
        mus.add(index, ModuleWrapper(LockerCabinet()))
        State.dataManager.currentManagementUnitIndex = index
        State.dataManager.currentLockerIndex = 0
        State.dataManager.mainFrame.drawLockerOverview()
    } //GEN-LAST:event_addMUnitRightLabelMouseReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private lateinit var addMUnitLeftLabel: JLabel
    private lateinit var addMUnitRightLabel: JLabel
    private lateinit var centerPanel: JPanel
    private lateinit var removeThisMUnitLabel: JLabel
    private lateinit var southPanel: JPanel
    private lateinit var transformLabel: JLabel

    init {
        initComponents()
        updatePanel()
    }
}